// app/head.js
export default function Head() {
  return (
    <>
      <title>My Next.js App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="/public/apple-touch-icon.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/public/favicon-32x32.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/public/favicon-16x16.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="192x192"
        href="/public/android-chrome-192x192.png"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="512x512"
        href="/public/android-chrome-512x512.png"
      />
      <link rel="manifest" href="/site.webmanifest" />
      {/* 추가로 다른 meta 태그나 링크 태그를 여기에 추가할 수 있습니다. */}
    </>
  );
}
